package com.linhuanjie.admin.model;

import java.io.Serializable;

/**
 *
 * Table:
 *   sys_permission
 *
 * @author Ant丶
 * @mbg.generated
 */
public class SysPermissionKey implements Serializable {
    /**
     *
     * Column:
     *   sys_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Description:
     *  This field corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Description:
     *  返回 sys_permission.id 的值
     *
     * @return 字段 sys_permission.id 的值
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * Description:
     *  设置 sys_permission.id 的值.
     *
     * @param id 字段 sys_permission.id 的值.
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return toString 的结果.
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return builder 的结果.
     * @mbg.generated
     */
    public static SysPermissionKey.Builder builder() {
        return new SysPermissionKey.Builder();
    }

    /**
     * Description:
     *  This class corresponds to the database table sys_permission
     *
     * @author Ant丶
     * @mbg.generated
     */
    public static class Builder {
        /**
         * Description:
         *  This field corresponds to the database table sys_permission
         *
         * @mbg.generated
         */
        private SysPermissionKey obj;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return Builder 的结果.
         * @mbg.generated
         */
        public Builder() {
            this.obj = new SysPermissionKey();
        }

        /**
         * Description:
         *  设置 sys_permission.id 的值.
         *
         * @param id 字段 sys_permission.id 的值.
         *
         * @mbg.generated
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return build 的结果.
         * @mbg.generated
         */
        public SysPermissionKey build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_permission
     *
     * @mbg.generated
     */
    public enum Column {
        id("id"),
        parentId("parent_id"),
        resName("res_name"),
        resType("res_type"),
        permission("permission"),
        url("url");

        /**
         * Description:
         *  This field corresponds to the database table sys_permission
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return value 的结果.
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return getValue 的结果.
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @param  column column
         * @return Column 的结果.
         * @mbg.generated
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return desc 的结果.
         * @mbg.generated
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return asc 的结果.
         * @mbg.generated
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}