package com.linhuanjie.admin.model;

import java.io.Serializable;

/**
 *
 * Table:
 *   sys_user
 *
 * @author Ant丶
 * @mbg.generated
 */
public class SysUserKey implements Serializable {
    /**
     *
     * Column:
     *   sys_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Description:
     *  This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Description:
     *  返回 sys_user.user_id 的值
     *
     * @return 字段 sys_user.user_id 的值
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Description:
     *  设置 sys_user.user_id 的值.
     *
     * @param userId 字段 sys_user.user_id 的值.
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return toString 的结果.
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return builder 的结果.
     * @mbg.generated
     */
    public static SysUserKey.Builder builder() {
        return new SysUserKey.Builder();
    }

    /**
     * Description:
     *  This class corresponds to the database table sys_user
     *
     * @author Ant丶
     * @mbg.generated
     */
    public static class Builder {
        /**
         * Description:
         *  This field corresponds to the database table sys_user
         *
         * @mbg.generated
         */
        private SysUserKey obj;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return Builder 的结果.
         * @mbg.generated
         */
        public Builder() {
            this.obj = new SysUserKey();
        }

        /**
         * Description:
         *  设置 sys_user.user_id 的值.
         *
         * @param userId 字段 sys_user.user_id 的值.
         *
         * @mbg.generated
         */
        public Builder userId(Long userId) {
            obj.setUserId(userId);
            return this;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return build 的结果.
         * @mbg.generated
         */
        public SysUserKey build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public enum Column {
        userId("user_id"),
        userName("user_name"),
        fullName("full_name"),
        password("password"),
        salt("salt");

        /**
         * Description:
         *  This field corresponds to the database table sys_user
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return value 的结果.
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return getValue 的结果.
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @param  column column
         * @return Column 的结果.
         * @mbg.generated
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return desc 的结果.
         * @mbg.generated
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return asc 的结果.
         * @mbg.generated
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}