package com.linhuanjie.admin.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * Table:
 *   sys_user
 *
 * @author Ant丶
 * @mbg.generated
 */
public class SysUser extends SysUserKey implements Serializable {
    /**
     *
     * Column:
     *   sys_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * Column:
     *   sys_user.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     *
     * Column:
     *   sys_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * Column:
     *   sys_user.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Description:
     *  This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Description:
     *  This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * Description:
     *  返回 sys_user.user_name 的值
     *
     * @return 字段 sys_user.user_name 的值
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Description:
     *  设置 sys_user.user_name 的值.
     *
     * @param userName 字段 sys_user.user_name 的值.
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Description:
     *  返回 sys_user.full_name 的值
     *
     * @return 字段 sys_user.full_name 的值
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Description:
     *  设置 sys_user.full_name 的值.
     *
     * @param fullName 字段 sys_user.full_name 的值.
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Description:
     *  返回 sys_user.password 的值
     *
     * @return 字段 sys_user.password 的值
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * Description:
     *  设置 sys_user.password 的值.
     *
     * @param password 字段 sys_user.password 的值.
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Description:
     *  返回 sys_user.salt 的值
     *
     * @return 字段 sys_user.salt 的值
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * Description:
     *  设置 sys_user.salt 的值.
     *
     * @param salt 字段 sys_user.salt 的值.
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return toString 的结果.
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", fullName=").append(fullName);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return builder 的结果.
     * @mbg.generated
     */
    public static SysUser.Builder builder() {
        return new SysUser.Builder();
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return hasSelective 的结果.
     * @mbg.generated
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return hasSelective 的结果.
     * @mbg.generated
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * Description: This method was generated by MyBatis Generator.
     *
     * @return selective 的结果.
     * @mbg.generated
     */
    public SysUser selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * Description:
     *  This class corresponds to the database table sys_user
     *
     * @author Ant丶
     * @mbg.generated
     */
    public static class Builder extends SysUserKey.Builder {
        /**
         * Description:
         *  This field corresponds to the database table sys_user
         *
         * @mbg.generated
         */
        private SysUser obj;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return Builder 的结果.
         * @mbg.generated
         */
        public Builder() {
            this.obj = new SysUser();
        }

        /**
         * Description:
         *  设置 sys_user.user_id 的值.
         *
         * @param userId 字段 sys_user.user_id 的值.
         *
         * @mbg.generated
         */
        public Builder userId(Long userId) {
            obj.setUserId(userId);
            return this;
        }

        /**
         * Description:
         *  设置 sys_user.user_name 的值.
         *
         * @param userName 字段 sys_user.user_name 的值.
         *
         * @mbg.generated
         */
        public Builder userName(String userName) {
            obj.setUserName(userName);
            return this;
        }

        /**
         * Description:
         *  设置 sys_user.full_name 的值.
         *
         * @param fullName 字段 sys_user.full_name 的值.
         *
         * @mbg.generated
         */
        public Builder fullName(String fullName) {
            obj.setFullName(fullName);
            return this;
        }

        /**
         * Description:
         *  设置 sys_user.password 的值.
         *
         * @param password 字段 sys_user.password 的值.
         *
         * @mbg.generated
         */
        public Builder password(String password) {
            obj.setPassword(password);
            return this;
        }

        /**
         * Description:
         *  设置 sys_user.salt 的值.
         *
         * @param salt 字段 sys_user.salt 的值.
         *
         * @mbg.generated
         */
        public Builder salt(String salt) {
            obj.setSalt(salt);
            return this;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return build 的结果.
         * @mbg.generated
         */
        public SysUser build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    public enum Column {
        userId("user_id"),
        userName("user_name"),
        fullName("full_name"),
        password("password"),
        salt("salt");

        /**
         * Description:
         *  This field corresponds to the database table sys_user
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return value 的结果.
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return getValue 的结果.
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @param  column column
         * @return Column 的结果.
         * @mbg.generated
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return desc 的结果.
         * @mbg.generated
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * Description: This method was generated by MyBatis Generator.
         *
         * @return asc 的结果.
         * @mbg.generated
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}