server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:mysql://39.105.56.62:3306/msy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    filters: stat,wall,slf4j
  application:
    name: admin
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
  redis:
    host: 39.105.56.62
    port: 6379

logging:
  file: ./logs/log.log
  level:
    root: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
